#!/bin/bash
 
VAR_FB=/var/lib/first-boot-setup
 
if [[ ! -d $VAR_FB ]] ; then
  mkdir $VAR_FB
fi
 
# checking if we already ran this script
if [[ -f $VAR_FB/initialized ]] ; then
  logger -t "first boot" "first boot setup already done, skipping"
  echo "first boot setup already done, skipping"
else
  dpkg -i /var/tmp/libnetfilter*.deb
  dpkg --force-confold -i /var/tmp/dnsmasq-base*.deb
  dpkg --force-confold -i /var/tmp/dnsmasq_*.deb
  dpkg --force-confold -i /var/tmp/hostapd*.deb
 
  ifdown wlan0
  ifup wlan0
   
  echo 'SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="%MAC%", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="wlan*", NAME="adm-wlan0"' >> /etc/udev/rules.d/70-persistent-net.rules
  sed -i "s/%MAC%/$(cat /sys/class/net/adm-wlan0/address)/g" /etc/udev/rules.d/70-persistent-net.rules
  sed -i "s/wlan0/adm-wlan0/g" /etc/network/interface
  sed -i "s/wlan0/adm-wlan0/g" /etc/dnsmasq.conf
  sed -i "s/wlan0/adm-wlan0/g" /etc/hostpad.conf
  touch $VAR_FB/initialized
   
  ifdown wlan0
  ifup adm-wlan0
 
  logger -t "first boot" "first boot setup done !"
  echo "first boot setup done !"
fi
 
exit 0
